Repository secure-software-engineering/phasar, pull requests merged in 2024-02, with the labels that each got.

#698 Misc Fixes
  include/phasar/DataFlow/IfdsIde/Solver/IDESolver.h
  include/phasar/PhasarLLVM/ControlFlow/LLVMBasedICFG.h
  include/phasar/PhasarLLVM/DB/LLVMProjectIRDB.h
  include/phasar/Utils/DFAMinimizer.h
  include/phasar/Utils/MaybeUniquePtr.h
  lib/PhasarLLVM/TaintConfig/LLVMTaintConfig.cpp
  unittests/Utils/CMakeLists.txt
  unittests/Utils/CompilationTests.cpp
Labels: bug

#701 Implementing On-The-Fly Reporting
  .clang-tidy
  .github/CODEOWNERS
  include/phasar/DataFlow/IfdsIde/IDETabulationProblem.h
  include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDETypeStateAnalysis.h
  include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/CSTDFILEIOTypeStateDescription.h
  include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLEVPKDFCTXDescription.h
  include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLEVPKDFDescription.h
  include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLSecureHeapDescription.h
  include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLSecureMemoryDescription.h
  include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/TypeStateDescription.h
  include/phasar/PhasarLLVM/Utils/AnalysisPrinterBase.h
  include/phasar/PhasarLLVM/Utils/DefaultAnalysisPrinter.h
  include/phasar/PhasarLLVM/Utils/LLVMIRToSrc.h
  include/phasar/PhasarLLVM/Utils/LLVMSourceManager.h
  include/phasar/PhasarLLVM/Utils/SourceMgrPrinter.h
  include/phasar/Utils/AnalysisPrinterBase.h
  include/phasar/Utils/DefaultAnalysisPrinter.h
  include/phasar/Utils/NullAnalysisPrinter.h
  include/phasar/Utils/OnTheFlyAnalysisPrinter.h
  lib/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEExtendedTaintAnalysis.cpp
  lib/PhasarLLVM/DataFlow/IfdsIde/Problems/IFDSTaintAnalysis.cpp
  lib/PhasarLLVM/DataFlow/IfdsIde/Problems/IFDSUninitializedVariables.cpp
  lib/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/CSTDFILEIOTypeStateDescription.cpp
  lib/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLEVPKDFCTXDescription.cpp
  lib/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLEVPKDFDescription.cpp
  lib/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLSecureHeapDescription.cpp
  lib/PhasarLLVM/DataFlow/IfdsIde/Problems/TypeStateDescriptions/OpenSSLSecureMemoryDescription.cpp
  lib/PhasarLLVM/Utils/LLVMIRToSrc.cpp
  lib/PhasarLLVM/Utils/LLVMSourceManager.cpp
  lib/PhasarLLVM/Utils/SourceMgrPrinter.cpp
  unittests/PhasarLLVM/ControlFlow/LLVMBasedICFGExportTest.cpp
  unittests/Utils/AnalysisPrinterTest.cpp
  unittests/Utils/CMakeLists.txt
  unittests/Utils/OnTheFlyAnalysisPrinterTest.cpp
  unittests/Utils/SourceMgrPrinterTest.cpp
Labels: enhancement

#697 IDE Statistics
  include/phasar/Controller/AnalysisController.h
  include/phasar/DataFlow/IfdsIde/EdgeFunction.h
  include/phasar/DataFlow/IfdsIde/EdgeFunctionStats.h
  include/phasar/DataFlow/IfdsIde/EdgeFunctionUtils.h
  include/phasar/DataFlow/IfdsIde/Solver/FlowEdgeFunctionCache.h
  include/phasar/DataFlow/IfdsIde/Solver/IDESolver.h
  include/phasar/DataFlow/IfdsIde/Solver/JumpFunctions.h
  include/phasar/Utils/Average.h
  include/phasar/Utils/Timer.h
  include/phasar/Utils/TypeTraits.h
  lib/Controller/AnalysisController.cpp
  lib/Controller/AnalysisControllerInternal.h
  lib/Controller/AnalysisControllerInternalIDE.h
  lib/Controller/AnalysisControllerInternalMono.h
  lib/Controller/AnalysisControllerXIDECSTDIOTS.cpp
  lib/Controller/AnalysisControllerXIDEIIA.cpp
  lib/Controller/AnalysisControllerXIDELinearConst.cpp
  lib/Controller/AnalysisControllerXIDEOpenSSLTS.cpp
  lib/Controller/AnalysisControllerXIDESolverTest.cpp
  lib/Controller/AnalysisControllerXIDEXTaint.cpp
  lib/Controller/AnalysisControllerXIFDSConst.cpp
  lib/Controller/AnalysisControllerXIFDSFieldSensTaint.cpp
  lib/Controller/AnalysisControllerXIFDSSolverTest.cpp
  lib/Controller/AnalysisControllerXIFDSTaint.cpp
  lib/Controller/AnalysisControllerXIFDSType.cpp
  lib/Controller/AnalysisControllerXIFDSUninit.cpp
  lib/Controller/AnalysisControllerXInterMonoSolverTest.cpp
  lib/Controller/AnalysisControllerXInterMonoTaint.cpp
  lib/Controller/AnalysisControllerXIntraMonoFullConstant.cpp
  lib/Controller/AnalysisControllerXIntraMonoSolverTest.cpp
  lib/PhasarLLVM/DataFlow/IfdsIde/Problems/IDELinearConstantAnalysis.cpp
  lib/Utils/EdgeFunctionStats.cpp
Labels: enhancement, refactoring

#699 Fix DebugLibDeps
  .github/workflows/ci.yml
  CMakeLists.txt
  cmake/phasar_macros.cmake
  config.h.in
  include/phasar.h
  include/phasar/DataFlow/IfdsIde/FlowFunctions.h
  include/phasar/DataFlow/IfdsIde/IDETabulationProblem.h
  include/phasar/PhasarLLVM/ControlFlow/LLVMBasedCFG.h
  include/phasar/PhasarLLVM/Pointer/LLVMPointsToUtils.h
  include/phasar/PhasarLLVM/Pointer/TypeGraphs/CachedTypeGraph.h
  include/phasar/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchy.h
  include/phasar/PhasarLLVM/Utils/LLVMShorthands.h
  lib/CMakeLists.txt
  lib/PhasarLLVM/ControlFlow/CMakeLists.txt
  lib/PhasarLLVM/ControlFlow/LLVMBasedCFG.cpp
  lib/PhasarLLVM/Passes/CMakeLists.txt
  lib/PhasarLLVM/Passes/GeneralStatisticsAnalysis.cpp
  lib/PhasarLLVM/Pointer/LLVMPointsToUtils.cpp
  lib/PhasarLLVM/Utils/LLVMShorthands.cpp
  tools/phasar-cli/CMakeLists.txt
  unittests/PhasarLLVM/TypeHierarchy/TypeGraphTest.cpp
Labels: bug, in-tree

#700 Fix IIA Edge Functions
  include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDEInstInteractionAnalysis.h
Labels: bug

#702 DI-based LLVM Type Hierarchy
  include/phasar/PhasarLLVM/TypeHierarchy/DIBasedTypeHierarchy.h
  include/phasar/PhasarLLVM/TypeHierarchy/LLVMVFTable.h
  lib/PhasarLLVM/TypeHierarchy/DIBasedTypeHierarchy.cpp
  lib/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchy.cpp
  test/llvm_test_code/type_hierarchies/CMakeLists.txt
  test/llvm_test_code/type_hierarchies/type_hierarchy_16.cpp
  test/llvm_test_code/type_hierarchies/type_hierarchy_17.cpp
  test/llvm_test_code/type_hierarchies/type_hierarchy_18.cpp
  test/llvm_test_code/type_hierarchies/type_hierarchy_19.cpp
  test/llvm_test_code/type_hierarchies/type_hierarchy_20.cpp
  test/llvm_test_code/type_hierarchies/type_hierarchy_21.cpp
  test/llvm_test_code/uninitialized_variables/struct_member_test.cpp
  unittests/PhasarLLVM/TypeHierarchy/CMakeLists.txt
  unittests/PhasarLLVM/TypeHierarchy/DIBasedTypeHierarchyTest.cpp
Labels: enhancement
