Repository secure-software-engineering/phasar, pull requests merged in 2025-02, with the labels that each got.

#743 Misc fixes
  CMakeLists.txt
  cmake/add_llvm.cmake
  cmake/phasar_macros.cmake
  include/phasar/DataFlow/IfdsIde/Solver/IFDSSolver.h
  include/phasar/DataFlow/Mono/Solver/IntraMonoSolver.h
  include/phasar/PhasarLLVM/ControlFlow/Resolver/CHAResolver.h
  include/phasar/PhasarLLVM/ControlFlow/Resolver/Resolver.h
  include/phasar/PhasarLLVM/DB/LLVMProjectIRDB.h
  include/phasar/PhasarLLVM/TaintConfig/TaintConfigData.h
  lib/PhasarLLVM/ControlFlow/Resolver/CHAResolver.cpp
  lib/PhasarLLVM/ControlFlow/Resolver/Resolver.cpp
  lib/PhasarLLVM/DB/LLVMProjectIRDB.cpp
Labels: cleanup, refactoring, technical debt

#744 feat/conan2
  .github/CODEOWNERS
  .gitignore
  .pre-commit-config.yaml
  CMakeLists.txt
  README.md
  cmake/add_llvm.cmake
  cmake/add_nlohmann_json.cmake
  cmake/phasar_macros.cmake
  conanfile.py
  include/phasar/Utils/GraphTraits.h
  lib/CMakeLists.txt
  lib/PhasarLLVM/DataFlow/PathSensitivity/CMakeLists.txt
  test_package/CMakeLists.txt
  test_package/conanfile.py
  test_package/example.ll
  test_package/myphasartool.cpp
  unittests/PhasarLLVM/DataFlow/PathSensitivity/CMakeLists.txt
  utils/conan/clang/conandata.yml
  utils/conan/clang/conanfile.py
  utils/conan/clang/patches/14x/0000-force-import-original-llvm-config.patch
  utils/conan/clang/test_package/CMakeLists.txt
  utils/conan/clang/test_package/conanfile.py
  utils/conan/clang/test_package/test_package.cpp
  utils/conan/llvm-core/conandata.yml
  utils/conan/llvm-core/conanfile.py
  utils/conan/llvm-core/patches/14x/0000-cmake-dependencies.patch
  utils/conan/llvm-core/patches/14x/0001-calculate-job-pools.patch
  utils/conan/llvm-core/patches/14x/0002-missing-includes.patch
  utils/conan/llvm-core/patches/14x/0003-no-build-with-install-rpath.patch
  utils/conan/llvm-core/patches/14x/0004-remove-lto-exports.patch
  utils/conan/llvm-core/test_package/CMakeLists.txt
  utils/conan/llvm-core/test_package/conanfile.py
  utils/conan/llvm-core/test_package/test_package.cpp
  utils/conan/test_conan_build.sh
Labels: usability, tooling

#742 Extract More Information from Debug Info
  cmake/phasar_macros.cmake
  include/phasar/DataFlow/IfdsIde/IDETabulationProblem.h
  include/phasar/DataFlow/IfdsIde/IFDSTabulationProblem.h
  include/phasar/DataFlow/PathSensitivity/PathSensitivityManagerBase.h
  include/phasar/PhasarLLVM/DataFlow/IfdsIde/LLVMFlowFunctions.h
  include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IDETypeStateAnalysis.h
  include/phasar/PhasarLLVM/Utils/LLVMIRToSrc.h
  include/phasar/Pointer/AliasInfo.h
  include/phasar/Pointer/AliasInfoBase.h
  include/phasar/Utils/BitVectorSet.h
  include/phasar/Utils/ByRef.h
  include/phasar/Utils/DebugOutput.h
  include/phasar/Utils/GraphTraits.h
  include/phasar/Utils/IotaIterator.h
  include/phasar/Utils/JoinLattice.h
  include/phasar/Utils/Macros.h
  include/phasar/Utils/PAMM.h
  include/phasar/Utils/TypeTraits.h
  include/phasar/Utils/Utilities.h
  lib/PhasarLLVM/DataFlow/IfdsIde/Problems/IDELinearConstantAnalysis.cpp
  lib/PhasarLLVM/Utils/LLVMIRToSrc.cpp
  unittests/PhasarLLVM/ControlFlow/LLVMBasedICFGExportTest.cpp
  unittests/PhasarLLVM/DataFlow/IfdsIde/InteractiveIDESolverTest.cpp
Labels: enhancement, cleanup, technical debt

#740 Simplifications in Helper Analyses
  include/phasar/PhasarLLVM/ControlFlow/LLVMBasedICFG.h
  include/phasar/PhasarLLVM/TaintConfig/TaintConfigData.h
  lib/PhasarLLVM/ControlFlow/LLVMBasedCallGraphBuilder.cpp
  lib/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchy.cpp
  lib/PhasarLLVM/TypeHierarchy/LLVMVFTable.cpp
  unittests/PhasarLLVM/TypeHierarchy/LLVMTypeHierarchyTest.cpp
Labels: technical debt

#723 Filtered AliasSet
  include/phasar/PhasarLLVM/DataFlow/IfdsIde/Problems/IFDSTaintAnalysis.h
  include/phasar/PhasarLLVM/Pointer/FilteredLLVMAliasSet.h
  include/phasar/PhasarLLVM/Pointer/LLVMAliasSet.h
  include/phasar/Pointer/AliasInfoTraits.h
  include/phasar/Utils/MaybeUniquePtr.h
  lib/PhasarLLVM/DataFlow/IfdsIde/Problems/IFDSTaintAnalysis.cpp
  lib/PhasarLLVM/Pointer/FilteredLLVMAliasSet.cpp
  unittests/PhasarLLVM/Pointer/CMakeLists.txt
  unittests/PhasarLLVM/Pointer/FilteredLLVMAliasSetTest.cpp
Labels: enhancement
